import {db,save,remove} from './api.js';import {can,serverAction,changePassword,downloadCSV} from './admin-api.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const field=(label,name,type='text',value='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" required></label>`;
const table=(headers,rows)=>`<div class="table-scroll"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(value=>`<td>${value}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
export function platformPanel(tab,{data,t,lang,caps}){
 const name=item=>esc(item[lang==='ar'?'name_ar':'name_en']||item[lang==='ar'?'title_ar':'title_en']);
 if(tab==='overview'){const activeUsers=data.profiles.filter(p=>p.last_active_at&&Date.parse(p.last_active_at)>Date.now()-7*86400000).length;const activeSubs=data.subscription_entitlements.filter(e=>['active','grace_period'].includes(e.status)&&Date.parse(e.expires_at)>Date.now()).length;const metrics=[[t('المستخدمون','Users'),data.profiles.length],[t('نشطون خلال ٧ أيام','Active in 7 days'),activeUsers],[t('اشتراكات فعالة','Active subscriptions'),activeSubs],[t('ثيمات منشورة','Published themes'),data.themes.filter(t=>['published','scheduled'].includes(t.status)).length]];return `<div class="grid">${metrics.map(([title,count])=>`<div class="card metric"><span>${title}</span><strong>${count}</strong></div>`).join('')}</div><div class="grid two"><div class="card"><h2>${t('استهلاك التجربة الفعلي','Actual trial usage')}</h2><strong>${Math.floor(data.trial_accounts.reduce((sum,item)=>sum+item.used_seconds,0)/60)} ${t('دقيقة','minutes')}</strong><p>${t('هذه أرقام الخادم، وليست بيانات معاينة.','These are server records, not preview data.')}</p>${data.trial_accounts.slice(0,8).map(item=>`<div class="usage-row"><code>${esc(item.user_id.slice(0,8))}</code><progress max="1800" value="${item.used_seconds}"></progress><span>${Math.floor(item.used_seconds/60)}/30</span></div>`).join('')}</div><div class="card"><h2>${t('أحدث العمليات','Latest operations')}</h2>${data.audit_logs.slice(0,8).map(item=>`<p>${esc(item.operation)} · ${esc(item.table_name)} <small>${esc(new Date(item.created_at).toLocaleString())}</small></p>`).join('')||t('لا توجد عمليات بعد','No operations yet')}</div></div>`;}
 if(tab==='music')return `<div class="grid two"><div class="card"><h2>${t('إضافة مقطع مرخّص','Add a licensed track')}</h2>${can(caps,'music.write')?`<form id="music-form">${field('العربية','name_ar')}${field('English','name_en')}${field(t('بيان حقوق الاستخدام','Usage rights note'),'rights_note')}<label>${t('الملف الصوتي','Audio file')}<input name="file" type="file" accept="audio/mpeg,audio/mp4,audio/wav,audio/aac" required></label><button>${t('رفع وحفظ','Upload and save')}</button></form>`:''}</div><div class="card"><h2>${t('قوائم التشغيل','Playlists')}</h2>${can(caps,'music.write')?`<form id="playlist-form"><label>${t('القائمة','Playlist')}<select name="id"><option value="">${t('قائمة جديدة','New playlist')}</option>${data.playlists.map(p=>`<option value="${p.id}">${name(p)}</option>`).join('')}</select></label>${field('العربية','name_ar')}${field('English','name_en')}<label>${t('معرّفات المقاطع مرتبة، مفصولة بفواصل','Ordered track IDs, comma-separated')}<textarea name="track_ids" required></textarea></label><label class="toggle-row"><input name="enabled" type="checkbox" checked>${t('تفعيل','Enabled')}</label><button>${t('حفظ القائمة','Save playlist')}</button></form>`:''}${data.playlists.map(p=>`<p>${name(p)} · ${p.enabled?'✓':'—'} ${can(caps,'music.write')?`<button class="danger" data-delete-playlist="${p.id}">${t('حذف','Delete')}</button>`:''}</p>`).join('')}</div></div><div class="card">${table([t('المقطع','Track'),'ID',t('الحقوق','Rights'),''],data.music.map(m=>[name(m),`<code>${esc(m.id)}</code>`,esc(m.rights_note),`<button class="secondary" data-play="${m.id}">${t('معاينة','Preview')}</button> ${can(caps,'music.write')?`<button class="secondary" data-toggle-track="${m.id}">${t(m.enabled?'تعطيل':'تفعيل',m.enabled?'Disable':'Enable')}</button> <button class="danger" data-remove-music="${m.id}">${t('حذف','Delete')}</button>`:''}`]))}</div>`;
 if(tab==='users')return `<div class="card"><div class="row"><h2>${t('المستخدمون','Users')}</h2><button id="export-users" class="secondary">CSV</button></div><label>${t('بحث بالاسم أو المدينة أو المعرّف','Search name, city or ID')}<input id="user-search"></label><div id="users-table">${table([t('الاسم','Name'),t('المدينة','City'),t('الحالة','Status'),t('الاشتراك','Subscription'),t('التسجيل','Joined'),t('آخر نشاط','Last activity'),''],data.profiles.map(p=>[esc(p.display_name),esc(p.city),esc(p.account_status),esc(data.subscription_entitlements.find(e=>e.user_id===p.user_id)?.status||'—'),esc(new Date(p.created_at).toLocaleDateString()),esc(p.last_active_at?new Date(p.last_active_at).toLocaleString():'—'),can(caps,'users.write')?`<button data-status-user="${p.user_id}" data-status="${p.account_status==='suspended'?'active':'suspended'}" class="secondary">${t(p.account_status==='suspended'?'تفعيل':'إيقاف',p.account_status==='suspended'?'Activate':'Suspend')}</button>`:'']))}</div></div>`;
 if(tab==='subscriptions')return `<div class="card"><div class="row"><h2>${t('الاستحقاقات الموثقة','Verified entitlements')}</h2><button id="export-subscriptions" class="secondary">CSV</button></div><p class="muted">${t('التسعير الترويجي المقترح ٨ دراهم لأول شهرين ثم ١٨؛ الأسعار الفعلية والعرض تحددهما Apple. السعر السنوي غير محدد. لا تُفعّل المدفوعات من هذه اللوحة.','Planned offer: AED 8 for the first two months, then AED 18. Apple controls actual storefront pricing and offer eligibility. Annual price is unset. Payments are not activated from this dashboard.')}</p>${table(['User','Product','Status','Environment','Expires'],data.subscription_entitlements.map(e=>[esc(e.user_id),esc(e.product_id),esc(e.status),esc(e.environment),esc(e.expires_at)]))}<h3>${t('الاستخدام التجريبي','Trial usage')}</h3>${table(['User','Seconds used','Remaining'],data.trial_accounts.map(e=>[esc(e.user_id),e.used_seconds,1800-e.used_seconds]))}<p>${t('ملخص الإيرادات يحتاج تقارير Apple المالية؛ لا نستنتج الإيراد من حالة الاشتراك.','Revenue totals require Apple financial reports; subscription status alone is not revenue.')}</p></div>`;
 if(tab==='religious')return `<div class="card"><h2>${t('محتوى موثّق المصدر','Source-documented content')}</h2>${can(caps,'content.write')?`<form id="religious-form"><div class="grid two">${field(t('عنوان عربي','Arabic title'),'title_ar')}${field(t('عنوان إنجليزي','English title'),'title_en')}</div><label>${t('المحتوى العربي','Arabic text')}<textarea name="text_ar" required></textarea></label><label>${t('المحتوى الإنجليزي','English text')}<textarea name="text_en" required></textarea></label><div class="grid two">${field(t('مرجع المصدر','Source reference'),'source_title')}${field(t('رابط المصدر','Source URL'),'source_url','url')}</div><label>${t('النوع','Type')}<select name="kind"><option value="adhkar">Adhkar</option><option value="dua">Dua</option><option value="hadith">Hadith</option></select></label><label class="toggle-row"><input name="verified" type="checkbox">${t('راجعت النص وصحته بالمصدر؛ أتحمل مسؤولية نشره','I reviewed the text against its source and take responsibility for publication')}</label><label>${t('الحالة','Status')}<select name="status"><option value="draft">Draft</option><option value="published">Published</option></select></label><button>${t('حفظ','Save')}</button></form>`:''}</div><div class="stack">${data.religious_content.map(item=>`<div class="card"><div class="row"><h3>${name(item)}</h3><span class="badge">${esc(item.status)}</span></div><p>${esc(item[lang==='ar'?'text_ar':'text_en'])}</p><a href="${esc(item.source_url)}" target="_blank" rel="noopener">${esc(item.source_title)}</a>${can(caps,'content.write')?`<div class="controls"><button data-religious-toggle="${item.id}" data-status="${item.status==='published'?'draft':'published'}">${t(item.status==='published'?'إلغاء نشر':'نشر',item.status==='published'?'Unpublish':'Publish')}</button><button data-religious-delete="${item.id}" class="danger">${t('حذف','Delete')}</button></div>`:''}</div>`).join('')}</div>`;
 if(tab==='staff')return `<div class="card"><h2>${t('الموظفون والصلاحيات','Staff & permissions')}</h2>${can(caps,'staff.write')?`<form id="staff-form"><div class="grid two">${field(t('البريد الإلكتروني','Email'),'email','email')}${field(t('كلمة المرور الأولية','Initial password'),'password','password')}</div><label>${t('الصلاحية','Role')}<select name="role_key">${data.roles.map(role=>`<option value="${role.key}">${esc(role[lang==='ar'?'name_ar':'name_en'])}</option>`).join('')}</select></label><button>${t('إنشاء موظف','Create staff account')}</button></form>`:''}${table(['User','Role','Enabled',''],data.staff_accounts.map(item=>[esc(item.user_id),esc(item.role_key),String(item.enabled),can(caps,'staff.write')?`<button data-staff-toggle="${item.user_id}" data-enabled="${!item.enabled}" class="secondary">${t(item.enabled?'تعطيل':'تفعيل',item.enabled?'Disable':'Enable')}</button>`:'']))}</div>`;
 if(tab==='audit')return `<div class="card"><h2>${t('سجل التغييرات','Audit log')}</h2>${table(['Time','Actor','Action','Table','Subject'],data.audit_logs.map(item=>[esc(new Date(item.created_at).toLocaleString()),esc(item.actor_id||'system'),esc(item.operation),esc(item.table_name),esc(item.subject_id)]))}</div>`;
 if(tab==='legal')return `<div class="card"><h2>${t('الوثائق القانونية','Legal documents')}</h2><p>${t('انشر فقط نصوصًا تطابق جمع البيانات وطريقة التشغيل الفعلية.','Publish text that matches actual data collection and service behavior.')}</p>${can(caps,'settings.write')?`<form id="legal-form"><label>${t('الوثيقة','Document')}<select name="id">${['privacy','terms','eula','subscription','refund','delete','retention','support'].map(id=>`<option>${id}</option>`).join('')}</select></label><div class="grid two">${field(t('العنوان العربي','Arabic title'),'title_ar')}${field(t('العنوان الإنجليزي','English title'),'title_en')}</div><label>${t('الأقسام العربية JSON: [[عنوان، نص]]','Arabic sections JSON: [[heading, text]]')}<textarea name="sections_ar" required></textarea></label><label>English sections JSON<textarea name="sections_en" required></textarea></label><label class="toggle-row"><input name="published" type="checkbox">${t('نشر','Publish')}</label><button>${t('حفظ','Save')}</button></form>`:''}${table(['Document','Version','Published'],data.legal_documents.map(item=>[esc(item.id),item.version,String(item.published)]))}</div>`;
 if(tab==='widgets')return `<div class="card"><h2>${t('أدوات الثيم','Theme widgets')}</h2><p>${t('كل ثيم يحدد الموضع والحجم والشفافية وصلاحيات التحريك والتغيير والإخفاء داخل محرر الثيم. واجهة السيارة تستخدم إمكانيات Apple فقط.','Each theme defines position, size, opacity and move/resize/hide permissions in its editor. Vehicle presentation uses only Apple-supported capabilities.')}</p>${table(['Widget','Arabic','English','Enabled'],data.widget_definitions.map(item=>[esc(item.id),esc(item.name_ar),esc(item.name_en),String(item.enabled)]))}<a href="/preview" data-link>${t('معاينة الأدوات','Preview widgets')}</a></div>`;
 return null;
}
export function extraSettings(data,t,caps){const settings=data.app_settings.find(s=>s.id==='public')?.value||{};return `<div class="card"><h2>${t('تغيير كلمة المرور','Change password')}</h2><form id="password-form">${field(t('كلمة المرور الحالية','Current password'),'current','password')}${field(t('كلمة المرور الجديدة','New password'),'new','password')}${field(t('تأكيد الكلمة الجديدة','Confirm password'),'confirm','password')}<button>${t('تغيير كلمة المرور','Change password')}</button></form></div>${can(caps,'settings.write')?`<div class="card"><h2>${t('التشغيل والتحديث','Runtime & updates')}</h2><form id="runtime-settings"><label class="toggle-row"><input name="maintenance" type="checkbox" ${settings.maintenance?'checked':''}>${t('وضع الصيانة','Maintenance mode')}</label><label class="toggle-row"><input name="splash_enabled" type="checkbox" ${settings.splash_enabled!==false?'checked':''}>${t('حركة البداية داخل التطبيق','In-app launch animation')}</label>${field(t('أقل إصدار مدعوم','Minimum supported version'),'minimum_version','text',settings.minimum_version||'0.1.0')}${field(t('تحديث المحتوى كل — ثانية','Content refresh — seconds'),'refresh_seconds','number',settings.refresh_seconds||600)}<button>${t('حفظ','Save')}</button></form></div>`:''}`;}
export function bindPlatform({data,t,lang,caps,run,refresh,flash}){
 const $=id=>document.getElementById(id),confirmDelete=()=>confirm(t('حذف نهائي؟','Delete permanently?'));
 if($('password-form'))$('password-form').onsubmit=e=>{e.preventDefault();run(async()=>{const f=new FormData(e.target);if(String(f.get('new')).length<8||f.get('new')!==f.get('confirm'))throw Error(t('تحقق من كلمة المرور الجديدة وتأكيدها','Check the new password and confirmation'));await changePassword(f.get('current'),f.get('new'));e.target.reset();flash(t('تم تغيير كلمة المرور وتسجيل خروج الجلسات الأخرى','Password changed; other sessions signed out'));});};
 if($('runtime-settings'))$('runtime-settings').onsubmit=e=>{e.preventDefault();run(async()=>{const f=new FormData(e.target),value={...(data.app_settings.find(s=>s.id==='public')?.value||{}),maintenance:f.has('maintenance'),splash_enabled:f.has('splash_enabled'),minimum_version:f.get('minimum_version'),refresh_seconds:Math.max(60,Math.min(86400,Number(f.get('refresh_seconds'))))};await save('app_settings',{id:'public',value});await refresh();});};
 if($('religious-form'))$('religious-form').onsubmit=e=>{e.preventDefault();run(async()=>{const record=Object.fromEntries(new FormData(e.target));record.id=crypto.randomUUID();record.verified=record.verified==='on';if(!record.source_url.startsWith('https://'))throw Error('HTTPS source required');if(record.status==='published'&&!record.verified)throw Error(t('راجع المصدر قبل النشر','Review the source before publication'));await save('religious_content',record);await refresh();});};
 document.querySelectorAll('[data-religious-toggle]').forEach(b=>b.onclick=()=>run(async()=>{const item=data.religious_content.find(r=>r.id===b.dataset.religiousToggle);await save('religious_content',{...item,status:b.dataset.status});await refresh();}));
 document.querySelectorAll('[data-religious-delete]').forEach(b=>b.onclick=()=>{if(confirmDelete())run(async()=>{await remove('religious_content',b.dataset.religiousDelete);await refresh();});});
 if($('staff-form'))$('staff-form').onsubmit=e=>{e.preventDefault();run(async()=>{const body={...Object.fromEntries(new FormData(e.target)),action:'create_staff'};await serverAction(body);e.target.reset();await refresh();});};
 document.querySelectorAll('[data-staff-toggle]').forEach(b=>b.onclick=()=>run(async()=>{const item=data.staff_accounts.find(s=>s.user_id===b.dataset.staffToggle);await save('staff_accounts',{...item,enabled:b.dataset.enabled==='true'});await refresh();}));
 document.querySelectorAll('[data-status-user]').forEach(b=>b.onclick=()=>run(async()=>{await serverAction({action:'user_status',user_id:b.dataset.statusUser,status:b.dataset.status});await refresh();}));
 if($('export-users'))$('export-users').onclick=()=>downloadCSV('wudcar-users.csv',data.profiles.map(({user_id,display_name,city,language,account_status,created_at,last_active_at})=>({user_id,display_name,city,language,account_status,created_at,last_active_at})));
 if($('export-subscriptions'))$('export-subscriptions').onclick=()=>downloadCSV('wudcar-subscriptions.csv',data.subscription_entitlements);
 if($('user-search'))$('user-search').oninput=e=>{const value=e.target.value.toLowerCase();document.querySelectorAll('#users-table tbody tr').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(value));};
 if($('playlist-form'))$('playlist-form').onsubmit=e=>{e.preventDefault();run(async()=>{const f=Object.fromEntries(new FormData(e.target)),id=f.id||crypto.randomUUID(),ids=f.track_ids.split(',').map(x=>x.trim()).filter(Boolean);if(new Set(ids).size!==ids.length||ids.some(id=>!data.music.some(m=>m.id===id)))throw Error(t('تحقق من معرّفات المقاطع وترتيبها','Check track IDs and ordering'));await save('playlists',{id,name_ar:f.name_ar,name_en:f.name_en,enabled:f.enabled==='on'});const cleared=await db.from('playlist_tracks').delete().eq('playlist_id',id);if(cleared.error)throw cleared.error;if(ids.length){const result=await db.from('playlist_tracks').insert(ids.map((track_id,sort_order)=>({playlist_id:id,track_id,sort_order})));if(result.error)throw result.error;}await refresh();});};
 document.querySelectorAll('[data-delete-playlist]').forEach(b=>b.onclick=()=>{if(confirmDelete())run(async()=>{await remove('playlists',b.dataset.deletePlaylist);await refresh();});});
 document.querySelectorAll('[data-toggle-track]').forEach(b=>b.onclick=()=>run(async()=>{const item=data.music.find(m=>m.id===b.dataset.toggleTrack);if(!item.enabled&&!item.rights_note?.trim())throw Error(t('سجل حقوق الاستخدام أولًا','Record usage rights first'));await save('music',{...item,enabled:!item.enabled});await refresh();}));
 if($('legal-form'))$('legal-form').onsubmit=e=>{e.preventDefault();run(async()=>{const f=Object.fromEntries(new FormData(e.target));for(const key of ['sections_ar','sections_en']){f[key]=JSON.parse(f[key]);if(!Array.isArray(f[key])||f[key].some(s=>!Array.isArray(s)||s.length!==2||s.some(v=>typeof v!=='string')))throw Error('Expected [[heading, text]]');}f.published=f.published==='on';f.version=(data.legal_documents.find(d=>d.id===f.id)?.version||0)+1;f.updated_at=new Date().toISOString();await save('legal_documents',f);await refresh();});};
}
