import {validateMediaURL} from '../../shared/domain.js';

const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={home:['الرئيسية','Home'],themes:['الثيمات','Themes'],library:['مكتبتي','Library'],settings:['الإعدادات','Settings']};
let model;try{model=JSON.parse(localStorage.getItem('wud-phone-preview'))||{};}catch{model={};}
model={name:'',city:'Dubai',clock:true,date:true,greeting:true,scale:1,opacity:1,sources:[],...model};
let current='home',period='morning',playerURL='',playerName='',kind='audio';
const icons={home:'⌂',themes:'✦',library:'▷',settings:'☷'};
const cities=[['Dubai','دبي'],['Abu Dhabi','أبوظبي'],['Sharjah','الشارقة'],['Fujairah','الفجيرة'],['Dibba','دبا'],['Ras Al Khaimah','رأس الخيمة'],['Ajman','عجمان'],['Umm Al Quwain','أم القيوين']];
let language='ar';
const tr=(ar,en)=>language==='ar'?ar:en;
const save=()=>localStorage.setItem('wud-phone-preview',JSON.stringify(model));
function greeting(){const hour=new Date().getHours();return tr(hour<12?'صباح الخير':'مساء الخير',hour<12?'Good morning':'Good evening')+(model.name?tr('، ', ', ')+model.name:'');}
function scene(compact=true){return `<div class="p-scene ${compact?'':'p-wide'}"><img src="/media/${compact?'compact':'ultrawide'}/${period}.png" alt="Spirit of the UAE — ${period}"><div class="p-shade"></div><div class="p-clock" style="opacity:${Number(model.opacity)};font-size:${Number(model.scale)}em">${model.clock?`<strong>${new Date().toLocaleTimeString(language==='ar'?'ar-AE':'en-GB',{hour:'2-digit',minute:'2-digit'})}</strong>`:''}${model.date?`<span>${new Date().toLocaleDateString(language==='ar'?'ar-AE':'en-GB',{weekday:'long',day:'numeric',month:'long'})}</span>`:''}${model.greeting?`<span>${escapeHTML(greeting())}</span>`:''}</div></div>`;}
function moments(){return `<div class="p-moments">${['dawn','morning','sunset','night'].map((p,i)=>`<button class="${p===period?'active':''}" data-p-moment="${p}">${tr(['الفجر','الصباح','المغرب','الليل'][i],['Dawn','Day','Sunset','Night'][i])}</button>`).join('')}</div>`;}
function body(){if(current==='home')return `<div class="p-hello"><span>${tr('رفيق مشاويرك','Your journey companion')}</span><h2>${escapeHTML(greeting())}</h2></div>${scene()}<div class="p-meta"><span>◉ ${escapeHTML(cities.find(c=>c[0]===model.city)?.[language==='ar'?1:0]||model.city)}</span><span>${tr('روح الإمارات','Spirit of the UAE')}</span></div>${moments()}<div class="p-panel"><div class="p-line"><h3>${tr('على ذوقك','Make it yours')}</h3><button data-p-tab="settings">${tr('تخصيص','Customize')} ←</button></div><p>${tr('اختر اسم التحية والمدينة والتفاصيل التي تحبها.','Choose your greeting name, city and the details you love.')}</p></div><div class="p-panel"><h3>${tr('وسائطك معك','Bring your media')}</h3><p>${tr('أضف مصدرًا تملك حق تشغيله وابدأ رحلتك.','Add a source you are authorized to play.')}</p><button data-p-tab="library" class="p-primary">${tr('افتح مكتبتي','Open my library')}</button></div>`;
if(current==='themes')return `<h2>${tr('أربع أوقات، روح واحدة','Four moments, one spirit')}</h2><p class="p-muted">${tr('روح الإمارات هو الثيم الافتراضي المعتمد.','Spirit of the UAE is the approved default theme.')}</p>${scene()}${moments()}<div class="p-line"><h3>${tr('روح الإمارات','Spirit of the UAE')}</h3><span class="p-chip">✓ ${tr('محدد','Selected')}</span></div><div class="p-mini-grid">${['dawn','morning','sunset','night'].map((p,i)=>`<button data-p-moment="${p}"><img src="/media/ultrawide/${p}.png" alt="${p}"><span>${tr(['الفجر','الصباح','المغرب','الليل'][i],['Dawn','Morning','Sunset','Night'][i])}</span></button>`).join('')}</div><p class="p-muted">${tr('معاينة العرض الطويل للشاشات المختلفة','Preview the wide layout')}</p>${scene(false)}`;
if(current==='library')return `<h2>${tr('كل ما تحب، قريب منك','Your favorites, within reach')}</h2><p class="p-muted">${tr('هذه تجربة تشغيل في المتصفح. توافق المصادر قد يختلف في الآيفون.','Playback here uses your browser. iPhone source compatibility may differ.')}</p><form id="p-source-form" class="p-panel"><label>${tr('اسم المصدر','Source name')}<input name="name" required maxlength="100" placeholder="${tr('مصدر الصوت الخاص بي','My audio source')}"></label><label>${tr('رابط HTTPS','HTTPS link')}<input name="url" type="url" required placeholder="https://" dir="ltr"></label><label>${tr('المحتوى','Media')}<select name="kind"><option value="audio">${tr('صوت','Audio')}</option><option value="video">${tr('فيديو','Video')}</option></select></label><button class="p-primary">+ ${tr('إضافة مصدر','Add source')}</button><p id="p-source-error" role="status"></p></form><label class="p-file">↗ ${tr('جرّب ملفًا من جهازك','Try a file from your device')}<input id="p-file" type="file" accept="audio/*,video/*"></label>${model.sources.length?model.sources.map((s,i)=>`<div class="p-source"><button data-p-play="${i}"><span>${s.kind==='video'?'▷':'♫'}</span>${escapeHTML(s.name)}</button><button data-p-delete="${i}" aria-label="${tr('حذف','Delete')}">×</button></div>`).join(''):`<div class="p-empty">▷<h3>${tr('مكتبتك جاهزة','Your library is ready')}</h3><p>${tr('المصادر التجريبية تحفظ في هذا المتصفح.','Preview sources are saved in this browser.')}</p></div>`}${playerURL?`<div class="p-panel"><h3>${escapeHTML(playerName)}</h3><${kind==='video'?'video':'audio'} controls autoplay src="${escapeHTML(playerURL)}" style="width:100%;max-height:200px"></${kind==='video'?'video':'audio'}><button id="p-stop">${tr('إيقاف','Stop')}</button></div>`:''}`;
return `<h2>${tr('تجربة تشبهك','A journey that feels like you')}</h2><form id="p-settings" class="p-panel"><label>${tr('اسم التحية — اختياري','Greeting name — optional')}<input name="name" value="${escapeHTML(model.name)}" maxlength="40"></label><label>${tr('المدينة','City')}<select name="city">${cities.map(c=>`<option value="${c[0]}" ${c[0]===model.city?'selected':''}>${c[language==='ar'?1:0]}</option>`).join('')}</select></label><div class="p-line"><span>${tr('اللغة','Language')}</span><button type="button" id="p-language">${language==='ar'?'English':'العربية'}</button></div>${['clock','date','greeting'].map((key,i)=>`<label class="p-toggle"><span>${tr(['الساعة','التاريخ','التحية'][i],['Clock','Date','Greeting'][i])}</span><input type="checkbox" name="${key}" ${model[key]?'checked':''}></label>`).join('')}<label>${tr('حجم النص','Text scale')}<input name="scale" type="range" min="0.8" max="1.3" step="0.05" value="${model.scale}"></label><label>${tr('الوضوح','Opacity')}<input name="opacity" type="range" min="0.5" max="1" step="0.05" value="${model.opacity}"></label><button class="p-primary">${tr('حفظ في المعاينة','Save preview preferences')}</button><span id="p-saved" role="status"></span></form><div class="p-panel"><h3>${tr('الحساب والاشتراك','Account & subscription')}</h3><p>${tr('تستخدم المعاينة كضيف. تفعيل الحساب والدفع يحتاج إعداد الخدمات الخارجية.','You are previewing as a guest. Accounts and payments require external service setup.')}</p></div><div class="p-policy-links"><a href="/privacy" data-link>${tr('الخصوصية','Privacy')}</a><a href="/terms" data-link>${tr('الشروط','Terms')}</a><a href="/delete" data-link>${tr('حذف الحساب','Account deletion')}</a></div>`;}
export function phonePreview(lang){language=lang;return `<main class="p-stage"><section class="p-intro"><span class="eyebrow">WUDCAR / LIVE PREVIEW</span><h1>${tr('جرّب رحلتك قبل أن تبدأ.','Take it for a spin.')}</h1><p>${tr('تنقّل بين صفحات التطبيق، غيّر الثيم وجرّب التحية باسمك.','Explore the app, choose a moment and try a greeting with your name.')}</p><div class="p-note">${tr('معاينة تفاعلية للمتصفح. تشغيل تطبيق الآيفون الأصلي يتم في Xcode؛ إعدادات التجربة تحفظ هنا فقط.','Interactive browser preview. The native iPhone app runs in Xcode; preview preferences stay in this browser.')}</div><a href="/admin-preview" data-link class="button">${tr('شاهد لوحة الإدارة','View the admin design')} ←</a><a href="/preview" data-link class="p-text-link">${tr('معاينة الشاشات العريضة','Preview wide screens')}</a></section><section class="p-device" dir="${language==='ar'?'rtl':'ltr'}"><div class="p-island"></div><div class="p-status"><span>WudCar</span><span>●●● ▰</span></div><div class="p-bar"><strong>${tr(...labels[current])}</strong><img src="/brand.png" alt="WudCar"></div><div id="p-content">${body()}</div><nav class="p-tabs">${Object.entries(labels).map(([key,text])=>`<button data-p-tab="${key}" class="${current===key?'active':''}"><span>${icons[key]}</span><small>${tr(...text)}</small></button>`).join('')}</nav><div class="p-home-indicator"></div></section></main>`;}
export function bindPhonePreview(rerender,setLanguage){
 document.querySelectorAll('[data-p-tab]').forEach(b=>b.onclick=()=>{current=b.dataset.pTab;rerender();});
 document.querySelectorAll('[data-p-moment]').forEach(b=>b.onclick=()=>{period=b.dataset.pMoment;rerender();});
 const form=document.querySelector('#p-settings');if(form)form.onsubmit=e=>{e.preventDefault();const f=new FormData(form);model={...model,name:String(f.get('name')).trim().slice(0,40),city:f.get('city'),scale:Number(f.get('scale')),opacity:Number(f.get('opacity')),clock:f.has('clock'),date:f.has('date'),greeting:f.has('greeting')};save();document.querySelector('#p-saved').textContent=tr('تم الحفظ ✓','Saved ✓');};
 const langButton=document.querySelector('#p-language');if(langButton)langButton.onclick=()=>setLanguage(language==='ar'?'en':'ar');
 const sourceForm=document.querySelector('#p-source-form');if(sourceForm)sourceForm.onsubmit=e=>{e.preventDefault();const f=new FormData(sourceForm);try{if(!validateMediaURL(f.get('url')))throw Error('Invalid URL');const url=new URL(f.get('url')).href;model.sources.push({name:String(f.get('name')).trim(),url,kind:f.get('kind')});save();rerender();}catch{document.querySelector('#p-source-error').textContent=tr('أدخل رابط HTTPS صالحًا دون بيانات دخول.','Enter a valid HTTPS URL without embedded credentials.');}};
 document.querySelectorAll('[data-p-play]').forEach(b=>b.onclick=()=>{const source=model.sources[Number(b.dataset.pPlay)];playerURL=source.url;playerName=source.name;kind=source.kind;rerender();});
 document.querySelectorAll('[data-p-delete]').forEach(b=>b.onclick=()=>{model.sources.splice(Number(b.dataset.pDelete),1);save();rerender();});
 const file=document.querySelector('#p-file');if(file)file.onchange=()=>{if(!file.files[0])return;if(playerURL.startsWith('blob:'))URL.revokeObjectURL(playerURL);playerURL=URL.createObjectURL(file.files[0]);playerName=file.files[0].name;kind=file.files[0].type.startsWith('video')?'video':'audio';rerender();};
 const stop=document.querySelector('#p-stop');if(stop)stop.onclick=()=>{if(playerURL.startsWith('blob:'))URL.revokeObjectURL(playerURL);playerURL='';rerender();};
}
